import type { TextUIDSL } from '../domain/dsl-types';
import type { ExportOptions, Exporter } from './export-types';
import { renderPageComponentsToStaticHtml } from './react-static-export';

const SCRIPT_SECTION = `<script lang="ts">
  // Generated by TextUI Designer.
</script>`;

const STYLE_SECTION = `<style>
  /* Tailwind classes are preserved in the generated markup. Enable Tailwind in the consuming app when you want those classes to take effect. */
</style>`;

function trimTrailingWhitespace(value: string): string {
  return value
    .split('\n')
    .map(line => line.trimEnd())
    .join('\n')
    .trim();
}

function indentBlock(content: string, spaces: number): string {
  const indent = ' '.repeat(spaces);
  return content
    .split('\n')
    .map(line => `${indent}${line}`)
    .join('\n');
}

function extractPrimaryMarkup(staticHtml: string): string {
  const normalizedHtml = trimTrailingWhitespace(staticHtml);
  const matched = normalizedHtml.match(/^<div\b[^>]*>([\s\S]*)<\/div>$/i);

  if (!matched) {
    return normalizedHtml;
  }

  return trimTrailingWhitespace(matched[1]);
}

function buildScriptSection(): string {
  return SCRIPT_SECTION;
}

function buildMarkupSection(dsl: TextUIDSL): string {
  const components = dsl.page?.components ?? [];
  const staticHtml = renderPageComponentsToStaticHtml(components);
  const fragment = extractPrimaryMarkup(staticHtml);
  const body = fragment ? `\n${indentBlock(fragment, 2)}\n` : '\n';

  return `<main class="textui-generated">
${body}</main>`;
}

function buildStyleSection(): string {
  return STYLE_SECTION;
}

export class SvelteExporter implements Exporter {
  async export(dsl: TextUIDSL, _options: ExportOptions): Promise<string> {
    return `${buildScriptSection()}

${buildMarkupSection(dsl)}

${buildStyleSection()}
`;
  }

  getFileExtension(): string {
    return '.svelte';
  }
}
