import type { TextUIDSL } from '../domain/dsl-types';
import type { ExportOptions, Exporter } from './export-types';
import { renderPageComponentsToStaticHtml } from './react-static-export';
import { extractPrimaryMarkup, indentBlock } from './framework-exporter-markup';
import { buildScriptExtensionPointComments } from './framework-exporter-script-extension-points';
import { buildThemeVariables } from './theme-definition-resolver';
import { buildThemeStyleBlock } from './theme-style-builder';
import { readWebviewCssIfPresent } from './html-template-builder';
import { SvelteComponentRenderer } from './svelte-native-renderer';
import { buildProtectedBlock, extractProtectedRegion } from './protected-region-utils';

function buildScriptSection(options: ExportOptions): string {
  const existingLogic = options.outputPath ? extractProtectedRegion(options.outputPath) : undefined;
  const protectedBlock = buildProtectedBlock(existingLogic);

  if (options.includeComments === false) {
    return `<script lang="ts">
  // Generated by TextUI Designer.
  ${protectedBlock}
</script>`;
  }

  return `<script lang="ts">
  // Generated by TextUI Designer.
${buildScriptExtensionPointComments('svelte')}

  ${protectedBlock}
</script>`;
}

function buildMarkupSection(dsl: TextUIDSL, options: ExportOptions): string {
  // Use native renderer by default, but allow opting out via options
  const useNative = options.useNativeFrameworkRenderer !== false;

  if (useNative) {
    const renderer = new SvelteComponentRenderer();
    const content = renderer.renderSvelteComponents(dsl);
    const body = content ? `\n${indentBlock(content, 2)}\n` : '\n';
    return `<main class="textui-generated">
${body}</main>`;
  }

  const components = dsl.page?.components ?? [];
  const staticHtml = renderPageComponentsToStaticHtml(components);
  const fragment = extractPrimaryMarkup(staticHtml);
  const body = fragment ? `\n${indentBlock(fragment, 2)}\n` : '\n';

  return `<main class="textui-generated">
${body}</main>`;
}

function buildStyleSection(options: ExportOptions): string {
  let themeStyles = '';
  if (options.themePath) {
    try {
      const allVars = buildThemeVariables(options.themePath);
      themeStyles = buildThemeStyleBlock(allVars);
    } catch (error) {
      console.warn(`[SvelteExporter] テーマ読み込みに失敗しました: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  const webviewCss = readWebviewCssIfPresent(options.extensionPath) || '';

  return `<style>
  /* Tailwind classes are preserved in the generated markup. Enable Tailwind in the consuming app when you want those classes to take effect. */
${webviewCss}
${themeStyles}
</style>`;
}

export class SvelteExporter implements Exporter {
  async export(dsl: TextUIDSL, options: ExportOptions): Promise<string> {
    return `${buildScriptSection(options)}

${buildMarkupSection(dsl, options)}

${buildStyleSection(options)}
`;
  }

  getFileExtension(): string {
    return '.svelte';
  }
}
