import type { TextUIDSL } from '../domain/dsl-types';
import type { ExportOptions, Exporter } from './export-types';
import { buildScriptExtensionPointComments } from './framework-exporter-script-extension-points';
import { buildFrameworkReactiveMarkup, buildVueBindingDeclarations } from './framework-reactive-parity';
import { buildThemeVariables } from './theme-definition-resolver';
import { buildThemeStyleBlock } from './theme-style-builder';
import { readWebviewCssIfPresent } from './html-template-builder';

function buildScriptSetupSection(options: ExportOptions, dsl: TextUIDSL): string {
  const { bindings } = buildFrameworkReactiveMarkup(dsl, 'vue');
  const bindingDeclarations = buildVueBindingDeclarations(bindings);

  if (options.includeComments === false) {
    return `<script setup lang="ts">
// Generated by TextUI Designer.
${bindingDeclarations ? `${bindingDeclarations}
` : ''}</script>`;
  }

  return `<script setup lang="ts">
// Generated by TextUI Designer.
${bindingDeclarations ? `${bindingDeclarations}
` : ''}${buildScriptExtensionPointComments('vue')}
</script>`;
}

function buildStyleSection(options: ExportOptions): string {
  let themeStyles = '';
  if (options.themePath) {
    try {
      const allVars = buildThemeVariables(options.themePath);
      themeStyles = buildThemeStyleBlock(allVars);
    } catch (error) {
      console.warn(`[VueExporter] テーマ読み込みに失敗しました: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  const webviewCss = readWebviewCssIfPresent(options.extensionPath) || '';

  return `<style scoped>
  /* Tailwind classes are preserved in the generated markup. Enable Tailwind in the consuming app when you want those classes to take effect. */
${webviewCss}
${themeStyles}
</style>`;
}

function buildTemplateSection(dsl: TextUIDSL): string {
  const { markup } = buildFrameworkReactiveMarkup(dsl, 'vue');
  const indented = markup
    .split('\n')
    .map(line => `  ${line}`)
    .join('\n');
  return `<template>
${indented}
</template>`;
}

export class VueExporter implements Exporter {
  async export(dsl: TextUIDSL, options: ExportOptions): Promise<string> {
    return `${buildTemplateSection(dsl)}

${buildScriptSetupSection(options, dsl)}

${buildStyleSection(options)}
`;
  }

  getFileExtension(): string {
    return '.vue';
  }
}
