import type { TextUIDSL } from '../renderer/types';
import type { ExportOptions, Exporter } from './export-types';
import { HtmlExporter } from './html-exporter';

function extractContainerContent(html: string): string {
  const matched = html.match(/<div class="container mx-auto p-6">([\s\S]*?)<\/div>\s*<\/body>/i);
  if (!matched) {
    return '';
  }
  return matched[1]
    .trim()
    .split('\n')
    .map(line => line.trimEnd())
    .join('\n');
}

function indent(content: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return content
    .split('\n')
    .map(line => `${pad}${line}`)
    .join('\n');
}

export class VueExporter implements Exporter {
  async export(dsl: TextUIDSL, _options: ExportOptions): Promise<string> {
    const html = await new HtmlExporter().export(dsl, { format: 'html' });
    const fragment = extractContainerContent(html);
    const templateBody = fragment ? `\n${indent(fragment, 4)}\n` : '\n';

    return `<template>
  <main class="textui-generated">
${templateBody}  </main>
</template>

<script setup lang="ts">
// Generated by TextUI Designer.
</script>

<style scoped>
/* Tailwindクラスを利用するため、利用側でTailwindを有効化してください。 */
</style>
`;
  }

  getFileExtension(): string {
    return '.vue';
  }
}
