import type { TextUIDSL } from '../domain/dsl-types';
import type { ExportOptions, Exporter } from './export-types';
import { HtmlExporter } from './html-exporter';
import { indentBlock, trimTrailingWhitespace } from './framework-exporter-markup';
import { buildScriptExtensionPointComments } from './framework-exporter-script-extension-points';
import { buildThemeVariables } from './theme-definition-resolver';
import { buildThemeStyleBlock } from './theme-style-builder';
import { readWebviewCssIfPresent } from './html-template-builder';
import { VueComponentRenderer } from './vue-native-renderer';
import { buildProtectedBlock, extractProtectedRegion } from './protected-region-utils';

function buildScriptSetupSection(options: ExportOptions): string {
  const existingLogic = options.outputPath ? extractProtectedRegion(options.outputPath) : undefined;
  const protectedBlock = buildProtectedBlock(existingLogic);

  if (options.includeComments === false) {
    return `<script setup lang="ts">
// Generated by TextUI Designer.
${protectedBlock}
</script>`;
  }

  return `<script setup lang="ts">
// Generated by TextUI Designer.
${buildScriptExtensionPointComments('vue')}

${protectedBlock}
</script>`;
}

function buildStyleSection(options: ExportOptions): string {
  let themeStyles = '';
  if (options.themePath) {
    try {
      const allVars = buildThemeVariables(options.themePath);
      themeStyles = buildThemeStyleBlock(allVars);
    } catch (error) {
      console.warn(`[VueExporter] テーマ読み込みに失敗しました: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  const webviewCss = readWebviewCssIfPresent(options.extensionPath) || '';

  return `<style scoped>
  /* Tailwind classes are preserved in the generated markup. Enable Tailwind in the consuming app when you want those classes to take effect. */
${webviewCss}
${themeStyles}
</style>`;
}

function extractContainerContent(html: string): string {
  const matched = html.match(/<body\b[^>]*>\s*<div\b[^>]*>([\s\S]*?)<\/div>\s*<\/body>/i);
  if (!matched) {
    return '';
  }

  return trimTrailingWhitespace(matched[1]);
}

function buildTemplateSection(dsl: TextUIDSL, options: ExportOptions, html: string): string {
  const useNative = options.useNativeFrameworkRenderer !== false;

  if (useNative) {
    const renderer = new VueComponentRenderer();
    const content = renderer.renderVueComponents(dsl);
    const templateBody = content ? `\n${indentBlock(content, 4)}\n` : '\n';
    return `<template>
  <main class="textui-generated">
${templateBody}  </main>
</template>`;
  }

  const fragment = extractContainerContent(html);
  const templateBody = fragment ? `\n${indentBlock(fragment, 4)}\n` : '\n';

  return `<template>
  <main class="textui-generated">
${templateBody}  </main>
</template>`;
}

export class VueExporter implements Exporter {
  async export(dsl: TextUIDSL, options: ExportOptions): Promise<string> {
    const useNative = options.useNativeFrameworkRenderer !== false;
    const html = useNative ? '' : await new HtmlExporter().export(dsl, { ...options, format: 'html' });

    return `${buildTemplateSection(dsl, options, html)}

${buildScriptSetupSection(options)}

${buildStyleSection(options)}
`;
  }

  getFileExtension(): string {
    return '.vue';
  }
}
