export const NAV_ERROR_CODES = {
  ENTRY_NOT_FOUND: 'NAV_001',
  TRANSITION_ENDPOINT_NOT_FOUND: 'NAV_002',
  PAGE_NOT_FOUND: 'NAV_003',
  CYCLE_DETECTED: 'NAV_004',
  UNREACHABLE_SCREEN: 'NAV_005',
  DUPLICATE_SCREEN_ID: 'NAV_006',
  DUPLICATE_TRANSITION_ID: 'NAV_007',
  TERMINAL_SCREEN_REQUIRED: 'NAV_008'
} as const;

export type NavErrorCode = typeof NAV_ERROR_CODES[keyof typeof NAV_ERROR_CODES];
