const assert = require('assert');
const { SvelteExporter } = require('../../out/exporters/svelte-exporter');
const { VueExporter } = require('../../out/exporters/vue-exporter');
const path = require('path');

describe('Framework Exporters Theme Support', () => {
  const themePath = path.resolve(__dirname, '../../sample/02-theme/textui-theme.yml');
  const dsl = {
    page: {
      id: 'test',
      title: 'Test',
      layout: 'vertical',
      components: [
        { Text: { value: 'Hello' } }
      ]
    }
  };

  describe('SvelteExporter Theme', () => {
    const exporter = new SvelteExporter();

    it('injects theme styles when themePath is provided', async () => {
      const output = await exporter.export(dsl, { format: 'svelte', themePath });

      assert.match(output, /--color-primary:/);
      assert.match(output, /--color-text-primary:/);
      assert.match(output, /\/\* textui-theme\.yml から反映されたテーマ \*\//);
    });

    it('omits extension comments when includeComments is false', async () => {
      const output = await exporter.export(dsl, { format: 'svelte', includeComments: false });

      assert.match(output, /\/\/ Generated by TextUI Designer\./);
      assert.doesNotMatch(output, /Reserved extension points/);
    });

    it('does not inject theme styles when themePath is missing', async () => {
      const output = await exporter.export(dsl, { format: 'svelte' });

      assert.doesNotMatch(output, /--brand-primary:/);
      assert.doesNotMatch(output, /\/\* textui-theme\.yml から反映されたテーマ \*\//);
    });
  });

  describe('VueExporter Theme', () => {
    const exporter = new VueExporter();

    it('injects theme styles when themePath is provided', async () => {
      const output = await exporter.export(dsl, { format: 'vue', themePath });

      assert.match(output, /--color-primary:/);
      assert.match(output, /--color-text-primary:/);
      assert.match(output, /\/\* textui-theme\.yml から反映されたテーマ \*\//);
    });

    it('omits extension comments when includeComments is false', async () => {
      const output = await exporter.export(dsl, { format: 'vue', includeComments: false });

      assert.match(output, /\/\/ Generated by TextUI Designer\./);
      assert.doesNotMatch(output, /Reserved extension points/);
    });

    it('does not inject theme styles when themePath is missing', async () => {
      const output = await exporter.export(dsl, { format: 'vue' });

      assert.doesNotMatch(output, /--brand-primary:/);
      assert.doesNotMatch(output, /\/\* textui-theme\.yml から反映されたテーマ \*\//);
    });
  });
});
